version: '3.0'

services:
  customer-frontend:
    image: nginx
    ports:
      - 81:80
    restart: unless-stopped
    volumes:
      - ./build:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
